### ISSUE TITLE
To add JavaScript (Videos) along with their learning notes on learn.everydaykarmaa.com Repo

### ISSUE THREAD

**Issue by isarojdahal** [isarojdahal/everydaykarmaa.com#10]
Video Topics and Link : 
https://www.youtube.com/playlist?list=PL4njvVBDLL23ldnM1oA0MJmRtbJJdkkah

![image](https://github.com/user-attachments/assets/7cebab36-e1a1-4633-b60d-224ca5b08594)

**Comment by Sanket2060** [comment]
I couldn't  understand how to add notes like should i create a link when clicked downloads the notes?I hope i am not the one to write notes for these videos right?So i need to create a videos (linking to youtube) and notes below it which gets downloaded during download button is clicked.Is this correct?

**Comment by isarojdahal** [comment]
This was the repo, in which it is associated with.
And, its PR is now merged
https://github.com/isarojdahal/learn.everydaykarmaa.com/pull/1
